language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements-dev.txt

# command to run tests
script:
  - pylama .
  - black --check .
  - py.test -s -v tests/test_sample.py
  - py.test -s -v tests/test_sample2.py
